name: flutter_live

description: Flutter live demo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.3.2
  dio: ^4.0.0
  pull_to_refresh: ^2.0.0
  keyboard_dismisser: ^2.0.0
  localstorage: ^4.0.0+1
  connectivity: ^3.0.3
  package_info: ^2.0.0
  app_settings: ^4.1.0
  crypto: ^3.0.1
  url_launcher: ^6.0.3
  permission_handler: ^6.1.3
  cached_network_image: ^3.0.0
  provider: ^5.0.0
  oktoast: ^3.0.0
  flutter_swiper_null_safety: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  share: ^2.0.4
  brightness_volume: ^1.0.3
  web_socket_channel: ^2.1.0
  flutter_barrage: ^0.5.0-nullsafety.0
  ftl_player: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/images/
